### ISSUE TITLE
_blockTracker wait for first block

### ISSUE THREAD

**Issue by Tectract** [MetaMask/provider-engine#149] opened 2017-05-24 05:11 UTC
Metamask is no longer working at all for me. web3.eth.accounts are not returned, even when connected to a localhost node.

All I get in the console is this error message:

"_blockTracker wait for first block"

Tested on multiple machines, latest chrome under ubuntu 14.04, same exact issue on a fresh install.

See: www.enledger.io/ethdeployer
source: github.com/tectract/ethdeployer

Help?

**Comment by flyswatter** [comment] 2017-05-24 16:51
We weren't able to reproduce this issue, but for this and other reasons, we rolled back yesterday's version bump, and will be refining it a bit before we release it again.

**Comment by orlandoc01** [comment] 2017-07-07 00:18
We are experiencing a similar error with our project. Currently running Node v6.5.0 and attempted to update `web3` to version 0.19.1 and `web3-provider-engine` to version 13.1.1 but it has resulted in a malfunctioning application. That is, any attempt to request for information is left hanging because the _blockTracker never manages to fetch the first block, and so `stoplight` never triggers a ready event.

After doing some digging, I realized the line that caused our application to malfunction after updating was the introduction of this additional boolean check. https://github.com/MetaMask/provider-engine/commit/cca54a0534df8f6168d10122eb72dabecfd2548b. We are using this library in a node environment, as specified above, and it seems another dependency required by `web3` is actually setting the `global.XMLHttpRequest` variable unexpectedly, with a library that has a slightly different API then the one assumed by this and so the request fails silently. Is there any reason to have this additional boolean check. Is just checking if the process is in the browser sufficient? Trying to figure out a way to get around this without forking the repo and editing `rpc.js` myself. (Editing the file locally within node_modules by deleting that extra boolean check restores the application to a functioning state).

**Comment by kumavis** [comment] 2017-07-07 01:37
@orlandoc01 i dont really remember why I added that -- maybe `process.browser` is erroneously falsely in some environments like webworkers

**Comment by kumavis** [comment] 2017-07-07 01:40
@Tectract node.js or browser?

**Comment by kumavis** [comment] 2017-07-07 01:45
@orlandoc01 that definitely seems like a bug that should be fixed on web3's side
looks like its coming from here
https://github.com/ethereum/web3.js/blob/0f53c43d7b0f3fbf6eba86bcd92373f3652537d1/lib/web3/httpprovider.js#L34

i would reccomend doing
```js
const Web3 = require('web3.js')
delete global.XMLHttpRequest
```
but actually i would highly recommend dropping web3.js entirely
try ethjs instead https://github.com/ethjs/ethjs

**Comment by orlandoc01** [comment] 2017-07-07 02:23
haha was just about to post that line but you found it already! Yeah, I just identified that as the problem, not a fan of messing with global variables though, or deleting them either, though I'm sure that work for this immediate issue (and hope it doesn't break anything else). Been having a lot of trouble with web3 lately so will definitely look into ethjs  for sure, thanks for the help!

**Comment by kumavis** [comment] 2017-07-07 02:25
yeah web3.js 0.x.x is also unmaintained and being deprecated as a standard (new standard will just be the web3.currentProvider interface)

**Comment by Tectract** [comment] 2017-07-07 05:47
Nice code investigation. We never actually identified the root cause of that bug. ethjs sounds interesting :) If global vars are the cause of the problem the answer is probably using namespaces...

**Closed** 2017-07-07 07:36 UTC
