### ISSUE TITLE
Support for web3 1.0

### ISSUE THREAD

**Issue by krzkaczor** [MetaMask/provider-engine#195] opened 2017-11-20 14:55 UTC
Hey,
any plans for support for web3 1.0 (currently in beta).

**Comment by danfinlay** [comment] 2017-11-20 20:09
Duplicate of #2350.

This just requires adding a websocket provider option, and we plan to do this, it's just not been a high priority. We may start putting bounties on issues like that soon, which is why we gave it the tag `bounty-worthy`.

**Closed by danfinlay** 2017-11-20 20:09 UTC
